#Data only container
data:
  extends:
    file: docker-compose.local.yml
    service: data_container

#Mysql server
mysql:
  image: mysql:latest
  expose:
    - "3306"
  ports:
    - "3306:3306"
  volumes_from:
    - data
  env_file: docker.env  

#Web layer
web:
    image: stefanorg/docker-apache-php
    ports:
        - "80:80"
    links:
        - mysql
    volumes_from:
        - data
    privileged: true
    env_file: docker.env
